// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// ir_rx //
// ----- //

#define ir_rx_wrap_target 0
#define ir_rx_wrap 12
#define ir_rx_pio_version 0

static const uint16_t ir_rx_program_instructions[] = {
            //     .wrap_target
    0x20a0, //  0: wait   1 pin, 0
    0x2020, //  1: wait   0 pin, 0
    0xa02b, //  2: mov    x, ~null
    0x00c5, //  3: jmp    pin, 5
    0x0043, //  4: jmp    x--, 3
    0xa0c9, //  5: mov    isr, ~x
    0x8000, //  6: push   noblock
    0xa02b, //  7: mov    x, ~null
    0x00c8, //  8: jmp    pin, 8
    0xa042, //  9: nop
    0xa0c9, // 10: mov    isr, ~x
    0x4001, // 11: in     pins, 1
    0x8000, // 12: push   noblock
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program ir_rx_program = {
    .instructions = ir_rx_program_instructions,
    .length = 13,
    .origin = -1,
    .pio_version = ir_rx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config ir_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ir_rx_wrap_target, offset + ir_rx_wrap);
    return c;
}

#include "hardware/clocks.h"
static inline void ir_rx_program_init(PIO pio, uint sm, uint offset, uint pin, float freq) {
    pio_sm_config c = ir_rx_program_get_default_config(offset);
    sm_config_set_in_pins(&c, pin);
    sm_config_set_jmp_pin(&c, pin);
    float div = (float)clock_get_hz(clk_sys) / freq;
    sm_config_set_clkdiv(&c, div);
    sm_config_set_in_shift(&c, false, false, 32);
    pio_gpio_init(pio, pin);
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, false);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

