// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// ir_tx //
// ----- //

#define ir_tx_wrap_target 0
#define ir_tx_wrap 2
#define ir_tx_pio_version 0

static const uint16_t ir_tx_program_instructions[] = {
            //     .wrap_target
    0x90a0, //  0: pull   block           side 0
    0xa027, //  1: mov    x, osr
    0x607f, //  2: out    null, 31
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program ir_tx_program = {
    .instructions = ir_tx_program_instructions,
    .length = 3,
    .origin = -1,
    .pio_version = ir_tx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config ir_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ir_tx_wrap_target, offset + ir_tx_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

